[variables]
    NIXPACKS_NODE_VERSION = '22.12.0'
    NODE_VERSION = '22.12.0'
    PNPM_FLAGS = '--force'

[phases.setup]
    nixPkgs = ['nodejs-22_x', 'pnpm-9_x']

[phases.install]
    cmds = ['pnpm install --frozen-lockfile --force']

[phases.build]
    cmds = ['pnpm run build']